#!/bin/bash
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# scripts/starter-hub/private-lb/hubenv.sh
#
# Generate the hub environment file (${HUB_ENV_FILE}, default
# .scratch/hub-<name>.env) that gce-start-hub.sh uploads to the VM.
#
# OAuth client IDs/secrets are pulled from Google Secret Manager at generate
# time — they are NEVER hard-coded or committed. Non-secret configuration
# (bucket, base URL, telemetry, image registry) is derived from config.sh.
# The SESSION_SECRET is reused from an existing env file if present, otherwise a
# fresh one is generated. Secret VALUES are never printed to stdout.
#
# Secret Manager secret names (override via *_SECRET_NAME env vars if different):
#   scion-hub-oauth-web-client-id      -> SCION_SERVER_OAUTH_WEB_GOOGLE_CLIENTID
#   scion-hub-oauth-web-client-secret  -> SCION_SERVER_OAUTH_WEB_GOOGLE_CLIENTSECRET
#   scion-hub-oauth-cli-client-id      -> SCION_SERVER_OAUTH_CLI_GOOGLE_CLIENTID
#   scion-hub-oauth-cli-client-secret  -> SCION_SERVER_OAUTH_CLI_GOOGLE_CLIENTSECRET

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=config.sh
source "${SCRIPT_DIR}/config.sh"

if [[ -z "${PROJECT_ID}" ]]; then
    echo "Error: PROJECT_ID is not set and could not be determined from gcloud config."
    exit 1
fi

WEB_ID_SECRET_NAME="${WEB_ID_SECRET_NAME:-scion-hub-oauth-web-client-id}"
WEB_SECRET_SECRET_NAME="${WEB_SECRET_SECRET_NAME:-scion-hub-oauth-web-client-secret}"
CLI_ID_SECRET_NAME="${CLI_ID_SECRET_NAME:-scion-hub-oauth-cli-client-id}"
CLI_SECRET_SECRET_NAME="${CLI_SECRET_SECRET_NAME:-scion-hub-oauth-cli-client-secret}"

# Fetch a secret's latest version. Exits non-zero (under set -e) if missing.
fetch_secret() {
    local name="$1"
    gcloud secrets versions access latest --secret "${name}" --project "${PROJECT_ID}"
}

echo "=== Generating hub env file: ${HUB_ENV_FILE} ==="
echo "Reading OAuth secrets from Secret Manager (project: ${PROJECT_ID})..."

WEB_CLIENT_ID="$(fetch_secret "${WEB_ID_SECRET_NAME}")"
WEB_CLIENT_SECRET="$(fetch_secret "${WEB_SECRET_SECRET_NAME}")"
CLI_CLIENT_ID="$(fetch_secret "${CLI_ID_SECRET_NAME}")"
CLI_CLIENT_SECRET="$(fetch_secret "${CLI_SECRET_SECRET_NAME}")"

# Reuse an existing SESSION_SECRET so restarts don't invalidate sessions.
SESSION_SECRET=""
if [[ -f "${HUB_ENV_FILE}" ]]; then
    SESSION_SECRET="$(grep -E '^SESSION_SECRET=' "${HUB_ENV_FILE}" | head -1 | cut -d= -f2- || true)"
fi
if [[ -z "${SESSION_SECRET}" ]]; then
    echo "Generating new SESSION_SECRET..."
    SESSION_SECRET="$(openssl rand -base64 32)"
else
    echo "Reusing existing SESSION_SECRET."
fi

# Non-secret config.
STORAGE_BUCKET="${SCION_HUB_STORAGE_BUCKET:-${PROJECT_ID}-scion-hub}"
BASE_URL="${SCION_SERVER_BASE_URL:-https://${HUB_DOMAIN}}"

mkdir -p "$(dirname "${HUB_ENV_FILE}")"
# Create with restrictive permissions from the outset.
umask 077
cat > "${HUB_ENV_FILE}" <<EOF
# Generated by hubenv.sh — DO NOT COMMIT. Contains OAuth secrets.
# Regenerate with: scripts/starter-hub/private-lb/hubenv.sh

# === Required ===
SCION_HUB_STORAGE_BUCKET=${STORAGE_BUCKET}
SESSION_SECRET=${SESSION_SECRET}

# === Hub & Registry ===
SCION_SERVER_BASE_URL=${BASE_URL}
SCION_IMAGE_REGISTRY=${SCION_IMAGE_REGISTRY}

# === OAuth — Web Clients (Google) ===
SCION_SERVER_OAUTH_WEB_GOOGLE_CLIENTID=${WEB_CLIENT_ID}
SCION_SERVER_OAUTH_WEB_GOOGLE_CLIENTSECRET=${WEB_CLIENT_SECRET}

# === OAuth — CLI Clients (Google) ===
SCION_SERVER_OAUTH_CLI_GOOGLE_CLIENTID=${CLI_CLIENT_ID}
SCION_SERVER_OAUTH_CLI_GOOGLE_CLIENTSECRET=${CLI_CLIENT_SECRET}

# === Telemetry (OTEL, GCP-native) ===
SCION_CLOUD_LOGGING=true
SCION_GCP_PROJECT_ID=${PROJECT_ID}
GOOGLE_CLOUD_PROJECT=${PROJECT_ID}
SCION_TELEMETRY_CLOUD_PROVIDER=gcp
SCION_OTEL_LOG_ENABLED=true

# === Maintenance (admin console "check for updates") ===
# Repo the hub fetches to compare HEAD vs origin/main. Without it the admin
# console reports "No repository path configured; set maintenance.repo_path".
SCION_MAINTENANCE_REPO_PATH=${REPO_DIR}
EOF
chmod 600 "${HUB_ENV_FILE}"

# Report success WITHOUT echoing any secret values.
ENTRY_COUNT="$(grep -cE '^[A-Z]' "${HUB_ENV_FILE}" || true)"
echo "  -> Wrote ${HUB_ENV_FILE} (${ENTRY_COUNT} entries, mode 600)"
echo "  -> Secret values were not printed."
